# Generated by Django 4.2.2 on 2023-06-17 17:03

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"default_manager_name": "published", "ordering": ["-publish"]},
        ),
        migrations.AlterModelManagers(
            name="post",
            managers=[
                ("published", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=250, unique_for_date="publish"),
        ),
    ]
